const express = require("express");
const cors = require("cors");
const dotenv = require("dotenv");
dotenv.config();
const shoppingRoutes = require("./routes/shoppingRoutes");
const app = express();
app.use(cors());
app.use(express.json());
app.use("/api/items", shoppingRoutes);
module.exports = app;